---
# handlers file for postgres
#
  - name: Restart service         #Handler для перезапуска сервиса Postgresql (если требуется)
    ansible.builtin.service:      # Модуль для работы с сервисами 
      name: "{{ pg_service }}"    #Имя сервиса, прописана в vars/main.yml
      state: restarted            #Статус рестарт
