---
# tasks file for postgres

###Install Postgresql###  ###В данном блоке устанавливается дополнительный пакет psycopg2, для работы официального модуля postgres от ansible.
  - name: "Install prerequisites"  
    yum:
      name: "python-psycopg2"
      state: "present"
      update_cache: "yes"

  - name: "Add Postgresql repo_key"  ### Добавляем ключ репозитория для установки postgres
    rpm_key:
      state: present
      key: "{{ pg_repo_key }}"

  - name: "Add Postgresql repo" ###Добавляем сам репозиторий через yum.
    yum:
      name: "{{ pg_repo }}"

  - name: "Install  Postgresql" ###Установка модуля postgresql-12-server. (Также можно установить другую версию, изменив переменную)
    yum:
      name: "{{ pg_version }}" 
      update_cache: yes
      state: present

#  - name: Creates directory   ###Здесь пытался инициализировать кластер в кастомную директорию, не работает корректно, с edb подобных проблем не было.
#    file:
#      path: /opt/data
#      state: directory
#      owner: postgres
#      group: postgres
#      mode: 0700
#
  - name: "Find out if PostgreSQL is initialized" #Проверка по файлу pg_hba.conf в дефолтной директории data, если файл есть, инициализация не выполнятеся, если файла нет, выполняется таск ниже.
    ansible.builtin.stat:
      path: "{{ pg_data }}/pg_hba.conf"
    register: postgres_data

  - name: "Initialize PostgreSQL"                  #Инициализация кластера в стандартной директории
    shell: "{{ pg_init }}"
    when: not postgres_data.stat.exists

  - name: "Start and enable services"              #Старт сервера postgres и добавление его в автозагрузку.
    service: "{{ pg_start_command}}"
    with_items:
        - "{{ pg_service }}"

###Config PostgreSQL###                           # Данный раздел позволяет вносить изменения в конфигурацию сервера с помошью модуля postgres 
                                                  # Команды выполняются как ALTER SYSTEM, записываются в файл postgresql.auto.conf, 
                                                  # для комманд требующих перезагрузку сервера postgres, настроен notify  - в случае изменения перезапускать
  - name: Set listen addresses parameter
    postgresql_set:
      name: listen_addresses
      value: '*'
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set work mem parameter
    postgresql_set:
      name: work_mem
      value: 32mb
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set max connection parameter
    postgresql_set:
      name: max_connections
      value: '1200'
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set effective cache size parameter
    postgresql_set:
      name: effective_cache_size
      value: 1536MB
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set shared buffers parameter
    postgresql_set:
      name: shared_buffers
      value: 512MB
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set max worker processes parameter
    postgresql_set:
      name: max_worker_processes
      value: '2'
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service

  - name: Set wal buffers parameter
    postgresql_set:
      name: wal_buffers
      value: 16MB
    register: set
    become:      yes
    become_user: postgres

  - name: Set max parallel workers parameter
    postgresql_set:
      name: max_parallel_workers
      value: '2'
    register: set
    become:      yes
    become_user: postgres
    notify: Restart service


###Add Roles for PostgreSQL###     ###Данный раздел позволяет добавлять/удалять пользователей, и предоставлять им определенные права, и добавлять запись в pg_hba.conf
                                   ### также с помощью модуля Ansible  - postgres

  - name: Create user for test
    postgresql_user:
      db: postgres
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      role_attr_flags: "SUPERUSER"
    become: yes
    become_user: postgres

#  - name: Remove User test
#    postgresql_user:
#      name: "{{ db_user }}"
#      state: absent
#    become: yes
#    become_user: postgres    

  - name: Add user in pg_hba.conf
    postgresql_pg_hba:
      dest: "{{ pg_data }}/pg_hba.conf"
      contype: host
      users: "{{ db_user }}"
      source: "{{ user_ip }}/32"
      databases: postgres
      method: md5

###Backup DB###    ### В данном разделе описывается механизм автоматизации резервного копирования. 
                   ### Создание директории для хранения бэкапа, создание директории для скрипта автоматизации

  - name: Backup directory   ### Создание директории для хранения бэкапа   
    ansible.builtin.file:
      path: "{{ backup_dir }}"
      mode: 0700
      owner: postgres
      state: directory
      ### С этого таска и ниже  можно указать delegeta_to указав alias реплики из inventory тогда все что ниже применится к серверу реплики для снятия БЭКАПА все директории.

  - name: Scripts directory ### Создание директории для хранения скриптов   
    ansible.builtin.file:
     path: /opt/scripts/
     mode: 0700
     owner: postgres
     state: directory
     

  - name: Backup Postgresql with script  ### Генерация скрипта с помощью шаблона jinja
    template:
      src: backup_db.j2 
      dest: "{{ scripts_dir }}/backup_db.sh"
      mode: 0700
      owner: postgres
      

  - name: Backup Postgres 1 day of month"  ###Добавления скрипта в задания Cron юзеру postgres, с запуском каждый первый день месяца в час ночи.
    ansible.builtin.cron:
      name: "backup_db"
      minute: "0"
      hour: "1"
      day: "1"
      job: "{{ scripts_dir }}/backup_db.sh"
    become: yes
    become_user: postgres 


#  - name: Backup db    ### Также таск по снятию дампа с объектов БД
#    community.postgresql.postgresql_db:
#      state: dump
#      name: "{{ db_name }}"
#      target: "{{ backup_dir }}/{{ db_name }}-{{ ansible_date_time.date }}.gz"
#    become: yes
#    become_user: postgres
