---

- name: Test DB install Postgesql  #Имя основного Task'a
  hosts: DB_TEST                   #Группа хостов из файла hosts, на котрых требуется выполнить playbook
  become: yes                      #Разрешает использование sudo/root
  roles: 
    - postgres                     #Роль которая будет запускать Tasks
